### PR TITLE
fix compression during serialization and workaround for incorrect BDC operand being serialized as an array

### LINKED ISSUE #221: Compression regression
Hi,

after upgrading to 0.8.2 (I skipped some versions) I noticed that my PDFs  files became 5x larger. After some investigation I found this:

https://github.com/fschutt/printpdf/blob/ccb7583b73b897c3c2ae77a4d587d909c28ced71/src/serialize.rs#L382

I manually added this line again in a local copy but this did not make a big difference. But maybe this was a debugging oversight?

I compared the generated PDFs and noticed that the older version was able to compress operations using object streams?

For my specific case I have a PDF with lots a drawing operations (rectangles, polygons). In 0.8.2 these are not compressed it seems, whereas previously this was the case. Is this correct? Is there a way to compress them also in 0.8.2?

### LINKED ISSUE #248: bug in serialize for BeginMarkedContentWithProperties
This op should have a dictionary as its second operand, not a vector of dictionaries.

As this would be an API break, a proper fix should be considered for a later release. For now, serialize should only use the first item of the vector as a workaround.

### LINKED ISSUE #251: Text state operators should be retained and not reset on BT during parsing
According to the documentation of Adobe:
```
The text state operators can appear outside text objects, and the values they set
are retained across text objects in a single content stream. Like other graphics
state parameters, these parameters are initialized to their default values at the
beginning of each page.
```
once any of those parameters are set, they should not reset at `BT` (begin text mode).

I will provide a fix for that tomorrow.

### PR DESCRIPTION
**Pull request by ronnybremer**
- provides a workaround when serializing a BeginMarkedContentWithProperties op, only use the first item in the properties vector, as the result needs to be a single dictionary, not an array of dictionaries
- a correct fix would break the API
- page content streams can be compressed, only fonts shouldn't
- fixes #221 
- fixes #248 
- fixes #251

### CODE REVIEW

**Comment by fschutt** [comment]
> a correct fix would break the API

Yeah, it's perfectly fine to break the API here, I'll take a look later today how to properly fix it. I was a bit lazy yesterday.

The content streams are intentionally not compressed for now, because there were issues with compressing fonts: https://github.com/J-F-Liu/lopdf/pull/9 

So, you could make an extra configuration variable "do you really want to compress ALL streams" to beta-enable it. My experience is that it breaks embedded fonts.

**Comment by ronnybremer** [comment]
> Yeah, it's perfectly fine to break the API here, I'll take a look later today how to properly fix it. I was a bit lazy yesterday.

For being lazy you were quite active :)
Anyway, if it's ok to break the API I can easily do that tomorrow if you agree, as I also want to add a proper `DrawRectangle` operation. Most of the time you just want that and it's quite more convenient than having to adjust a `Polygon`. It also serializes into a single operation: `re`.

> So, you could make an extra configuration variable "do you really want to compress ALL streams" to beta-enable it. My experience is that it breaks embedded fonts.

I don't think thats necessary, as you already mark all font streams as `don't compress`:
https://github.com/fschutt/printpdf/blob/61e27490d311c5177cfa26ef6a98fccac8143c7c/src/serialize.rs#L1144-L1149

I did debug the produced PDF with compression turned on and the fonts are not compressed, the page content stream is. Looks fine to me.

File: src/serialize.rs [hunk 1]
```diff
@@ -1385,6 +1387,10 @@ fn color_array_to_f32(c: &ColorArray) -> Vec<f32> {
 
 // Encode text to UTF-16BE with BOM
 fn encode_text_to_utf16be(text: &str) -> lopdf::Object {
+    if text.is_empty() {
+        return lopdf::Object::string_literal("");
+    }
+
```
Comment (ronnybremer) [inline src/serialize.rs:1428]: this makes sure we don't serialize ```<FEFF>``` for empty dictionary entires

**Comment by ronnybremer** [comment]
I broke the API, therefore a few examples had to be updated as well. My tests are working well, looking forward to your input.

File: src/ops.rs [hunk 2]
```diff
@@ -373,15 +375,21 @@ pub enum Op {
...
     DefineMarkedContentPoint {
         tag: String,
         properties: Vec<DictItem>,
     },
     /// Ends the current marked-content sequence.
     EndMarkedContent,
+    /// Ends the current marked-content sequence.
+    EndMarkedContentWithProperties,
+    /// Ends the current optional content sequence.
+    EndOptionalContent,
```
Comment (ronnybremer) [inline src/ops.rs:392]: those two are practically the same as EndLayer, but for a user of this crate it is more consistent to end each marked content op with a similar named Op

File: src/deserialize.rs [hunk 3]
```diff
@@ -2233,6 +2241,8 @@ pub fn parse_op(
         "n" => {
             // End path without filling or stroking
             state.path_builder.clear();
+            out_ops.extend_from_slice(&state.rectangle_builder.get_ops());
```
Comment (ronnybremer) [inline src/deserialize.rs:2244]: won't output any Ops if there is no current rectangle being worked on

**Comment by ronnybremer** [comment]
How did I break those tests 🤔

**Comment by ronnybremer** [comment]
Looks like the latest version of `read-fonts` has an issue:
[googlefonts-1693](https://github.com/googlefonts/fontations/issues/1693)
and of course, just released last night :)

**Comment by LaurenzV** [comment]
> So, you could make an extra configuration variable "do you really want to compress ALL streams" to beta-enable it. My experience is that it breaks embedded fonts.

I would be curious where you encountered that issue? Do you have a sample PDF? I've never had any issues displaying PDFs with compressed fonts, and that would also be a very weird exception which I haven't seen mentioned in any PDF specification.

**Comment by ronnybremer** [comment]
> I would be curious where you encountered that issue? Do you have a sample PDF? I've never had any issues displaying PDFs with compressed fonts, and that would also be a very weird exception which I haven't seen mentioned in any PDF specification.

I think the warning came from here:
[https://github.com/J-F-Liu/lopdf/blob/c1728b11012eb8e661f0a9f71e2039d14aa7a023/src/object.rs#L620-L623](https://github.com/J-F-Liu/lopdf/blob/c1728b11012eb8e661f0a9f71e2039d14aa7a023/src/object.rs#L620-L623)

**Comment by ronnybremer** [comment]
@fschutt could you please re-run the checks, the issue in `read-fonts` should be fixed by now. Thank you!

**Comment by ronnybremer** [comment]
Ahh, much better. Thank you @fschutt :)

Would you mind accepting that PR, if it looks ok to you, as I am not a big fan of large PRs, so I could continue working on the CFF idea.
